Product implement
anji907/mokumoku pull request #2
Opened 2023-04-17 05:48 UTC by anji907

# 事業をエンジニアリングしよう 実装編
レビューよろしくお願いします！
## 選択した事業課題
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？

## テスト結果
### 1/2
<img width="1040" alt="スクリーンショット 2023-04-17 13 11 12" src="https://user-images.githubusercontent.com/70253960/232393181-4a02ae8e-fe96-4b6d-9d96-5cb37b43f738.png">

### 2/2
<img width="940" alt="スクリーンショット 2023-04-17 13 11 17" src="https://user-images.githubusercontent.com/70253960/232393458-a6a0830f-10ea-4a4d-a877-0f8c9dbc676d.png">

2023-04-17 10:25 UTC, busitora requested changes

2023-04-17 10:25 UTC, busitora commented on app/controllers/relationships_controller.rb
> +    current_user.unfollow(@user)
unfollow メソッドの中に `Relationship.find(params[:id]).followed` を移譲させましょう。また、なかった場合の処理も考慮して下さい

2023-04-17 10:25 UTC, busitora commented on app/controllers/users_controller.rb
> +  def show
@user = User.find(params[:id]) ですが同じ記述が2箇所以上出た場合は before_action 等でまとめるといいかと！

2023-04-17 10:25 UTC, busitora commented on app/models/user.rb
> +    following.destroy(other_user)
following が nil な場合、どのような挙動になりますか？

2023-04-17 10:25 UTC, busitora commented on spec/decorators/relationship_decorator_spec.rb
> +require 'rails_helper'
不要なファイルは削除して下さい

2023-04-17 10:25 UTC, busitora commented on spec/factories/relationships.rb
> +FactoryBot.define do
不要なファイルは削除して下さい

2023-04-17 10:25 UTC, busitora commented on spec/models/relationship_spec.rb
> +require 'rails_helper'
不要なファイルは削除して下さい

2023-04-17 10:25 UTC, busitora commented on spec/requests/relationships_spec.rb
> +require 'rails_helper'
不要なファイルは削除して下さい

2023-04-18 03:16 UTC, anji907 commented
修正しました。レビューお願いします！
[7bd8f99](https://github.com/anji907/mokumoku/pull/2/commits/7bd8f9986e42fddece6f1908168fcadf904cbca7)
[1c8e540](https://github.com/anji907/mokumoku/pull/2/commits/1c8e54087b109abc184d8145c71e562c792c8d2d)
[d1881d1](https://github.com/anji907/mokumoku/pull/2/commits/d1881d198724fdc45c18ce38a422c857d4a96509)

## テスト結果
<img width="815" alt="スクリーンショット 2023-04-18 12 05 01" src="https://user-images.githubusercontent.com/70253960/232661780-2e54bd91-a274-4d9d-a672-f0db4ab21e4d.png">

<img width="816" alt="スクリーンショット 2023-04-18 12 05 05" src="https://user-images.githubusercontent.com/70253960/232661816-95059473-bb22-4faf-9299-f693ab3a8eda.png">

2023-04-18 10:20 UTC, takyyk commented
LGTMです！

余談ですが、指摘された箇所に関する修正事項はリプライの形でまとめておくとレビューの際に見やすいですね。

2023-04-19 02:18 UTC, anji907 commented
> LGTMです！
> 
> 余談ですが、指摘された箇所に関する修正事項はリプライの形でまとめておくとレビューの際に見やすいですね。

2023-04-19 02:21 UTC, merged